server:
  context-path: /uaa
  port: 5000

management:
  security:
    enabled: false
  context-path: /mgmt
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: ALWAYS

eureka:
  instance:
    health-check-url-path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}



spring:
  datasource:
    url: jdbc:mysql://10.203.72.183:3306/eshop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
