spring:
  application:
    name: zipkin
  rabbitmq:
    host: 10.203.72.183
    port: 5672
    virtual-host: /mine
    username: mine
    password: mine

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
