logging:
  level:
    org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter: error

server:
  port: 8040

turbine:
  combine-host-port: true
  app-config: gateway,svca-service,svcb-service,auth-service
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:8761/eureka/

spring:
  rabbitmq:
    host: 10.203.72.183
    port: 5672
    virtual-host: /mine
    username: mine
    password: mine
#boot:
      ##    admin:
      ##      routes:
      ##        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      ##      turbine:
    ##        clusters: default
    ##        location: http://127.0.0.1:${turbine.stream.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
security:
  user:
    name: admin
    password: ${MONITOR_SERVER_PASSWORD:admin}