server:
  port: 8761

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  security:
    user:
      name: user
      password: ${REGISTRY_SERVER_PASSWORD:password}
